"""Run status transition helper for the Python monitor service.

Mirrors web/server/lib/run-status.ts so that transitions driven by the
stale-run monitor and threshold triggers participate in the same
precedence-based state machine as API-driven transitions.

The helper:
  * locks the run row with SELECT ... FOR UPDATE so we cannot race with
    the Node backend (or another Python instance) writing to the same run,
  * enforces terminal precedence (FAILED > CANCELLED > TERMINATED > COMPLETED)
    for the "api" source only -- our internal sources (stale-monitor,
    threshold-trigger) are deliberate backend actions and bypass precedence,
  * elides no-op transitions so the timeline is free of duplicates,
  * inserts a row into run_status_events when (and only when) the state
    actually changed.

Usage:
    from python.run_status import transition_run_status
    transition_run_status(
        session,
        run_id=run.id,
        to_status="FAILED",
        source="stale-monitor",
        metadata={"grace_seconds": grace},
    )

The caller is responsible for `session.commit()` as before; this helper
does not commit, so the event and the status mutation land atomically.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Literal, Optional

from sqlalchemy import text
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

TransitionSource = Literal["api", "resume", "stale-monitor", "threshold-trigger"]

# Must mirror web/server/lib/run-status.ts SEVERITY. Higher wins when two
# terminal transitions race.
_SEVERITY = {
    "RUNNING": -1,
    "COMPLETED": 0,
    "TERMINATED": 1,
    "CANCELLED": 2,
    "FAILED": 3,
}

_TERMINAL = {"COMPLETED", "FAILED", "CANCELLED", "TERMINATED"}

# Name of the Postgres enum type generated by Prisma for RunStatus. Kept as a
# single constant so that if the Prisma enum is ever renamed (or a custom
# @@map is added to web/server/prisma/schema.prisma) only one spot needs to
# change. See the `enum RunStatus` block in schema.prisma.
_RUN_STATUS_ENUM = "RunStatus"


def transition_run_status(
    session: Session,
    *,
    run_id: int,
    to_status: str,
    source: TransitionSource,
    metadata: Optional[dict[str, Any]] = None,
) -> bool:
    """Transition a run to `to_status`, emitting a status event when appropriate.

    Returns True if the run was updated, False if the write was a no-op or
    rejected by precedence. Does not commit the session.
    """
    # Row-lock the run so concurrent writers serialise.
    row = session.execute(
        text("SELECT status FROM runs WHERE id = :id FOR UPDATE"),
        {"id": run_id},
    ).fetchone()

    if row is None:
        logger.warning("transition_run_status: run %s not found", run_id)
        return False

    from_status = row[0]
    # SQLAlchemy may return either an enum or a string depending on binding
    if hasattr(from_status, "value"):
        from_status = from_status.value

    # Precedence: reject lower-severity terminal overwriting higher-severity.
    # Only applies to `api` source -- backend sources bypass.
    if (
        source == "api"
        and from_status in _TERMINAL
        and to_status in _TERMINAL
        and _SEVERITY[to_status] < _SEVERITY[from_status]
    ):
        logger.info(
            "transition_run_status: rejecting %s -> %s for run %s (precedence)",
            from_status,
            to_status,
            run_id,
        )
        return False

    # Always refresh statusUpdated so clients can see liveness of the writer.
    if metadata is not None:
        session.execute(
            text(
                'UPDATE runs SET status = :status, "statusUpdated" = NOW(), '
                '"statusMetadata" = CAST(:meta AS JSONB) WHERE id = :id'
            ),
            {
                "status": to_status,
                "meta": json.dumps(metadata),
                "id": run_id,
            },
        )
    else:
        session.execute(
            text('UPDATE runs SET status = :status, "statusUpdated" = NOW() WHERE id = :id'),
            {"status": to_status, "id": run_id},
        )

    # Elide no-op transitions -- DDP fan-out collapses to a single event.
    if from_status == to_status:
        return True

    session.execute(
        text(
            "INSERT INTO run_status_events ("
            '"runId", "fromStatus", "toStatus", source, metadata, "createdAt"'
            f') VALUES (:run_id, CAST(:from_status AS "{_RUN_STATUS_ENUM}"), '
            f'CAST(:to_status AS "{_RUN_STATUS_ENUM}"), :source, CAST(:meta AS JSONB), NOW())'
        ),
        {
            "run_id": run_id,
            "from_status": from_status,
            "to_status": to_status,
            "source": source,
            "meta": json.dumps(metadata) if metadata is not None else None,
        },
    )

    return True
