/**
 * ESLint configuration for @mlop/server
 *
 * Includes custom rules for Prisma query optimization to prevent
 * performance issues like OOM under high load.
 */

import tseslint from 'typescript-eslint';
import noUnboundedPrismaInclude from './eslint-rules/no-unbounded-prisma-include.js';

/** @type {import('eslint').Linter.Config[]} */
export default [
  // Ignore node_modules and build output
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'dist/**',
      'eslint-rules/**', // Don't lint the rules themselves
      'next-env.d.ts',   // Auto-generated by Next.js
    ],
  },

  // TypeScript configuration
  ...tseslint.configs.recommended,

  // Custom Prisma rules
  {
    // Apply to all TypeScript files
    files: ['**/*.ts', '**/*.tsx'],

    plugins: {
      '@mlop': {
        rules: {
          'no-unbounded-prisma-include': noUnboundedPrismaInclude,
        },
      },
    },

    rules: {
      // Disable some strict rules that are too noisy for existing codebase
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'prefer-const': 'off',

      // Warn on unbounded Prisma includes to prevent OOM
      // Change to 'error' once existing code is fixed
      '@mlop/no-unbounded-prisma-include': [
        'warn',
        {
          // Relations that are safe to include unbounded (e.g., 1:1 relations, always small)
          allowedRelations: [
            'organization', // 1:1 relation
            'user',         // 1:1 relation
            'project',      // 1:1 relation
            'apiKey',       // 1:1 relation
          ],
        },
      ],
    },
  },
];
