-- Refreshable materialized view that recomputes per-(run, metric) summary
-- stats every 5 minutes from raw deduped data into mlop_metric_summaries_v2.
--
-- Companion to 02b_metric_summaries_v2.sql. Lives alongside the original
-- mlop_metric_summaries_mv (03_*), which still incrementally feeds the v1
-- mlop_metric_summaries — see 02b for the reasoning behind the
-- side-by-side layout.
--
-- Why a refreshable MV instead of an incremental one:
--   The old mlop_metric_summaries_mv aggregated each ingest batch into the
--   summary table without dedup. Its per-batch partials had no concept of
--   "this step was already logged" and would just add to the running
--   sum/count, corrupting aggregates for any run that re-logged steps
--   (resume / eval rerun / manual fix).
--
--   This MV reads from mlop_metrics_v2 with FINAL, which collapses
--   duplicate (run, metric, step) rows at the engine level (latest `time`
--   wins). The aggregate functions then operate on already-deduped data,
--   producing correct min/max/sum/count regardless of how many times a
--   step was re-written.
--
-- APPEND mode: each refresh writes one row per (run, metric) with
-- version_at_compute = now(). The target table's
-- ReplacingMergeTree(version_at_compute) engine collapses successive
-- versions by keeping the highest-version row. Reads use FINAL to dedup
-- before background merges complete.
--
-- 5-minute interval is a starting point — staleness vs cluster load
-- trade-off. Effective worst-case staleness is interval + compute_time.
-- Tune via ALTER TABLE … MODIFY REFRESH if needed; do not edit this file
-- in place for a running deployment.
CREATE MATERIALIZED VIEW IF NOT EXISTS mlop_metric_summaries_v2_refresh_mv
REFRESH EVERY 5 MINUTE
APPEND
TO mlop_metric_summaries_v2
AS SELECT
    tenantId,
    projectName,
    runId,
    logName,
    minIf(value, isFinite(value))                          AS min_value,
    maxIf(value, isFinite(value))                          AS max_value,
    sumIf(value, isFinite(value))                          AS sum_value,
    toUInt64(countIf(isFinite(value)))                     AS count_value,
    argMaxStateIf(value, step, isFinite(value))            AS last_value,
    sumIf(value * value, isFinite(value))                  AS sum_sq_value,
    min(step)                                              AS min_step,
    max(step)                                              AS max_step,
    argMinStateIf(step, value, isFinite(value))            AS argmin_step,
    argMaxStateIf(step, value, isFinite(value))            AS argmax_step,
    toUInt64(toUnixTimestamp64Milli(now64(3)))             AS version_at_compute
FROM mlop_metrics_v2 FINAL
GROUP BY tenantId, projectName, runId, logName
