/**
 * Generates a complete inventory of the backend's HTTP surface.
 *
 * The OpenAPI spec at /api/openapi.json only covers the machine-to-machine
 * REST API (/api/runs/*, bearer auth). It says nothing about the ~94 tRPC
 * procedures the web app itself calls, which are the larger half of the
 * surface and authenticate differently (better-auth session cookie — an API
 * key does NOT open them). Anyone reviewing or security-testing this backend
 * from the outside would silently miss all of it.
 *
 * This script walks the live routers and writes both halves to
 * docs/api-surface.{md,json}: every tRPC procedure with its call shape, auth
 * tier and input JSON Schema, plus the REST endpoints from the OpenAPI
 * document, plus the routes that appear in neither.
 *
 * The same walk backs the session-gated OpenAPI document at
 * /api/docs/openapi-trpc.json, so the inventory and the interactive docs can
 * never disagree about what exists.
 *
 * Run: pnpm --filter @mlop/server inventory
 * The output is committed, so `git diff` after a run shows surface drift.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import app from "../index";
import {
  collectTrpcProcedures,
  type TrpcAuthTier,
  type TrpcProcedureSummary,
} from "../lib/trpc-surface";

interface ProcedureEntry extends TrpcProcedureSummary {
  url: string;
}

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

/**
 * Routes served by plain Hono routers. They carry no OpenAPI metadata and no
 * tRPC definition, so nothing can enumerate them automatically — they are
 * listed by hand and must be kept in step with web/server/index.ts.
 */
const UNDOCUMENTED_ROUTES: Array<{ route: string; auth: string; note: string }> = [
  { route: "ALL /api/auth/*", auth: "varies (better-auth)", note: "sign-in/up, sessions, 2FA, SSO/SAML, organization + member + invitation management" },
  { route: "GET /api/chart-data/multi-metric-batch-bucketed", auth: "session OR bearer key", note: "hybrid auth; org access checked against the session's membership or the key's bound org" },
  { route: "POST /api/slug", auth: "bearer key", note: "resolves the key's organization slug" },
  { route: "ALL /api/integrations/*", auth: "session / OAuth callback", note: "Linear OAuth connect + callback" },
  { route: "POST /api/stripe/*", auth: "Stripe signature", note: "billing webhook; verified by signature, not by session" },
  { route: "GET /api/docs, /api/docs/session", auth: "session", note: "authenticated Swagger UI" },
  { route: "POST /api/docs/key, /api/docs/key/revoke", auth: "session + x-mlop-docs header", note: "mints/revokes the temporary docs API key" },
  { route: "GET /api/health, /api/health/ready, /api/version", auth: "none", note: "liveness/readiness/build info" },
  { route: "GET /metrics", auth: "internal only (:8080)", note: "Prometheus metrics, separate port" },
];

function collectProcedures(): ProcedureEntry[] {
  return collectTrpcProcedures().map((procedure) => ({
    ...procedure,
    // Queries carry the superjson envelope in the query string; mutations POST it.
    url:
      procedure.httpMethod === "GET"
        ? `/trpc/${procedure.path}?input={"json":<input>}`
        : `/trpc/${procedure.path}`,
  }));
}

function collectRestEndpoints() {
  const document = app.getOpenAPIDocument({
    openapi: "3.0.0",
    info: { title: "mlop API", version: "1.0.0" },
  });

  return Object.entries(document.paths ?? {})
    .flatMap(([path, operations]) =>
      Object.entries(operations as Record<string, { summary?: string }>)
        .filter(([method]) =>
          ["get", "post", "put", "patch", "delete"].includes(method),
        )
        .map(([method, operation]) => ({
          method: method.toUpperCase(),
          path,
          summary: operation.summary ?? "",
        })),
    )
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

function markdown(
  procedures: ProcedureEntry[],
  rest: ReturnType<typeof collectRestEndpoints>,
): string {
  const byAuth = (tier: TrpcAuthTier) =>
    procedures.filter((procedure) => procedure.auth === tier).length;

  const lines: string[] = [];
  lines.push("# Backend HTTP surface");
  lines.push("");
  lines.push(
    "Generated by `pnpm --filter @mlop/server inventory` — do not edit by hand.",
  );
  lines.push("");
  lines.push(
    "Three separate surfaces, three different credentials. The published " +
      "OpenAPI spec covers only the first.",
  );
  lines.push("");
  lines.push("| Surface | Endpoints | Credential |");
  lines.push("|---|---|---|");
  lines.push(
    `| REST API (\`/api/runs/*\`) | ${rest.length} | \`Authorization: Bearer <api key>\` |`,
  );
  lines.push(
    `| tRPC (\`/trpc/*\`) | ${procedures.length} | better-auth session cookie — **API keys are not accepted** |`,
  );
  lines.push(
    `| Other Hono routes | ${UNDOCUMENTED_ROUTES.length} groups | varies, see below |`,
  );
  lines.push("");
  lines.push("## tRPC procedures");
  lines.push("");
  lines.push(
    "Auth tiers: `public` (no credential), `session` (signed in), " +
      `\`session+org\` (signed in **and** a member of the \`organizationId\` passed in the input). ` +
      `Counts: ${byAuth("public")} public, ${byAuth("session")} session, ${byAuth("session+org")} session+org.`,
  );
  lines.push("");
  lines.push(
    "`session+org` procedures take the organization from caller-supplied " +
      "input and then verify membership, so the input is the thing to fuzz.",
  );
  lines.push("");
  lines.push("Calling convention (tRPC v11, superjson):");
  lines.push("");
  lines.push("```bash");
  lines.push("# query");
  lines.push(
    `curl -b cookies.txt '<PUBLIC_URL>/trpc/organization.listMembers?input={"json":{"organizationId":"<org>"}}'`,
  );
  lines.push("# mutation");
  lines.push(
    `curl -b cookies.txt -X POST '<PUBLIC_URL>/trpc/runs.updateTags' \\`,
  );
  lines.push(`  -H 'Content-Type: application/json' \\`);
  lines.push(`  -d '{"json":{"organizationId":"<org>","runId":"<sqid>"}}'`);
  lines.push("```");
  lines.push("");
  lines.push("| Procedure | Kind | Auth | HTTP |");
  lines.push("|---|---|---|---|");
  for (const procedure of procedures) {
    lines.push(
      `| \`${procedure.path}\` | ${procedure.type} | ${procedure.auth} | ${procedure.httpMethod} \`/trpc/${procedure.path}\` |`,
    );
  }
  lines.push("");
  lines.push(
    "Input JSON Schemas for every procedure are in `api-surface.json` " +
      "(`procedures[].input`).",
  );
  lines.push("");
  lines.push("### Notes for anyone testing this surface");
  lines.push("");
  lines.push(
    "- **A bearer API key does not authenticate tRPC.** `createContext` reads " +
      "only the better-auth session, so every `/trpc/*` call needs the session " +
      "cookie; a valid `mlps_` key returns 401 there.",
  );
  lines.push(
    "- The client batches by default: `?batch=1&input={\"0\":{\"json\":<input>}}`, " +
      "and the response is an array — `response[0].result.data.json`.",
  );
  lines.push(
    "- Queries also accept POST (the server sets `allowMethodOverride`), so a " +
      "read can arrive as either verb.",
  );
  lines.push(
    "- Errors come back as `{\"error\":{\"json\":{...}}}` with an HTTP status in " +
      "`error.json.data.httpStatus`. A `data.stack` field means the target is " +
      "**not** running with `NODE_ENV=production`.",
  );
  lines.push(
    "- Run ids in tRPC inputs are SQIDs (see `lib/sqids.ts`), not the numeric " +
      "database ids the REST API returns.",
  );
  lines.push("");
  lines.push("## REST API (in the OpenAPI spec)");
  lines.push("");
  lines.push("| Method | Path | Summary |");
  lines.push("|---|---|---|");
  for (const endpoint of rest) {
    lines.push(`| ${endpoint.method} | \`${endpoint.path}\` | ${endpoint.summary} |`);
  }
  lines.push("");
  lines.push("## Routes in neither the spec nor tRPC");
  lines.push("");
  lines.push("| Route | Auth | Notes |");
  lines.push("|---|---|---|");
  for (const route of UNDOCUMENTED_ROUTES) {
    lines.push(`| \`${route.route}\` | ${route.auth} | ${route.note} |`);
  }
  lines.push("");
  return lines.join("\n");
}

const procedures = collectProcedures();
const rest = collectRestEndpoints();

writeFileSync(
  join(REPO_ROOT, "docs", "api-surface.json"),
  `${JSON.stringify({ procedures, rest, other: UNDOCUMENTED_ROUTES }, null, 2)}\n`,
);
writeFileSync(
  join(REPO_ROOT, "docs", "api-surface.md"),
  markdown(procedures, rest),
);

console.log(
  `Wrote docs/api-surface.{md,json}: ${procedures.length} tRPC procedures, ${rest.length} REST endpoints.`,
);
